# Generated by Django 6.0.5 on 2026-07-12 21:34

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_historicalaccount'),
        ('common', '0024_alter_customfielddefinition_target_model'),
        ('opportunity', '0010_opportunity_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOpportunity',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Opportunity Name')),
                ('stage', models.CharField(choices=[('PROSPECTING', 'Prospecting'), ('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='PROSPECTING', max_length=64, verbose_name='Stage')),
                ('opportunity_type', models.CharField(blank=True, choices=[('NEW_BUSINESS', 'New Business'), ('EXISTING_BUSINESS', 'Existing Business'), ('RENEWAL', 'Renewal'), ('UPSELL', 'Upsell'), ('CROSS_SELL', 'Cross-sell')], max_length=64, null=True, verbose_name='Type')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD, Dollar'), ('EUR', 'EUR, Euro'), ('GBP', 'GBP, Pound'), ('INR', 'INR, Rupee'), ('CAD', 'CAD, Dollar'), ('AUD', 'AUD, Dollar'), ('JPY', 'JPY, Yen'), ('CNY', 'CNY, Yuan'), ('CHF', 'CHF, Franc'), ('SGD', 'SGD, Dollar'), ('AED', 'AED, Dirham'), ('BRL', 'BRL, Real'), ('MXN', 'MXN, Peso')], max_length=3, null=True, verbose_name='Currency')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount')),
                ('amount_source', models.CharField(choices=[('MANUAL', 'Manual'), ('CALCULATED', 'Calculated from Products')], default='MANUAL', max_length=20, verbose_name='Amount Source')),
                ('probability', models.IntegerField(blank=True, default=0, null=True, verbose_name='Probability (%)')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='Expected Close Date')),
                ('lead_source', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('CALL', 'CALL'), ('EMAIL', ' EMAIL'), ('EXISTING CUSTOMER', 'EXISTING CUSTOMER'), ('PARTNER', 'PARTNER'), ('PUBLIC RELATIONS', 'PUBLIC RELATIONS'), ('CAMPAIGN', 'CAMPAIGN'), ('WEBSITE', 'WEBSITE'), ('OTHER', 'OTHER')], max_length=255, null=True, verbose_name='Lead Source')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Per-org schema extension; values are validated against common.CustomFieldDefinition.')),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Stage Changed At')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account')),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'historical Opportunity',
                'verbose_name_plural': 'historical Opportunities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
